# Generated by Django 3.1.4 on 2020-12-10 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlmacenModel',
            fields=[
                ('almacenId', models.AutoField(db_column='alma_id', primary_key=True, serialize=False, unique=True)),
                ('almacenDescripcion', models.CharField(db_column='alma_desc', max_length=45)),
            ],
            options={
                'verbose_name': 'Almacen',
                'verbose_name_plural': 'Almacenes',
                'db_table': 't_almacen',
            },
        ),
        migrations.CreateModel(
            name='CabeceraVentaModel',
            fields=[
                ('cabeceraVentaId', models.AutoField(db_column='cabven_id', primary_key=True, serialize=False, unique=True)),
                ('cabeceraVentaFecha', models.DateTimeField(db_column='cabven_fecha')),
                ('cabeceraVentaTotal', models.DecimalField(db_column='cabven_total', decimal_places=2, max_digits=5)),
                ('cabeceraVentaNombre', models.CharField(db_column='cabven_nomb', max_length=45)),
            ],
            options={
                'db_table': 't_cabventa',
            },
        ),
        migrations.CreateModel(
            name='ProductoModel',
            fields=[
                ('productoId', models.AutoField(auto_created=True, db_column='prod_id', primary_key=True, serialize=False, unique=True)),
                ('productoNombre', models.CharField(db_column='prod_nom', max_length=45)),
                ('productoPrecio', models.DecimalField(db_column='prod_prec', decimal_places=2, max_digits=5)),
                ('productoMinimo', models.IntegerField(db_column='prod_minimo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 't_producto',
            },
        ),
        migrations.CreateModel(
            name='ProductoAlmacenModel',
            fields=[
                ('productoAlmacenId', models.AutoField(db_column='prod_alma_id', primary_key=True, serialize=False, unique=True)),
                ('productoAlmacenCantidad', models.IntegerField(db_column='prod_alma_cant')),
                ('almacenId', models.ForeignKey(db_column='alma_id', on_delete=django.db.models.deletion.PROTECT, related_name='almacenesProductos', to='administracion.almacenmodel')),
                ('productoId', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='productosAlmacenes', to='administracion.productomodel')),
            ],
            options={
                'db_table': 't_prod_alma',
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaModel',
            fields=[
                ('detalleVentaId', models.AutoField(db_column='detven_id', primary_key=True, serialize=False, unique=True)),
                ('detalleVentaCantidad', models.IntegerField(db_column='detven_cant')),
                ('detalleVentaSubTotal', models.DecimalField(db_column='detven_subtotal', decimal_places=2, max_digits=5)),
                ('cabeceraVentaId', models.ForeignKey(db_column='cabven_id', on_delete=django.db.models.deletion.PROTECT, related_name='cabeceraVentas', to='administracion.cabeceraventamodel')),
                ('productoAlmacenId', models.ForeignKey(db_column='prod_alma_id', on_delete=django.db.models.deletion.PROTECT, related_name='productoAlmacenVentas', to='administracion.productoalmacenmodel')),
            ],
            options={
                'db_table': 't_detventa',
            },
        ),
    ]
