# Generated by Django 3.1.4 on 2020-12-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacenmodel',
            name='almacenDescripcion',
            field=models.CharField(db_column='alma_desc', max_length=75, verbose_name='Descripcion del almacen'),
        ),
    ]
