# Generated by Django 3.1.4 on 2020-12-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_auto_20201212_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacenmodel',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
