# Generated by Django 3.1.4 on 2020-12-16 00:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_almacenmodel_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoalmacenmodel',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, db_column='fecCreacion', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoalmacenmodel',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_column='fecActualizacion'),
        ),
    ]
