# Generated by Django 3.1.4 on 2020-12-16 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_auto_20201215_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventamodel',
            name='productoAlmacenId',
        ),
        migrations.AddField(
            model_name='detalleventamodel',
            name='productoId',
            field=models.ForeignKey(db_column='prod_id', default=None, on_delete=django.db.models.deletion.PROTECT, related_name='productoVentas', to='administracion.productomodel'),
            preserve_default=False,
        ),
    ]
